import 'models/product-model.dart';

List<Category> categoryData = [
  Category(
    id: 1,
    name: 'کرم',
  ),
  Category(
    id: 2,
    name: 'شامپو',
  ),
  Category(
    id: 3,
    name: 'ژل',
  ),
  Category(
    id: 4,
    name: 'سرم',
  ),
  Category(
    id: 5,
    name: 'فوم',
  ),
  Category(
    id: 6,
    name: 'پن',
  ),
  Category(
    id: 7,
    name: 'لوسیون',
  ),
  Category(
    id: 8,
    name: 'روغن',
  ),
];

List<Brands> brandData = [
  Brands(
    id: 1,
    name: "درمالیفت",
    latinName: "Dermalift",
    image: "images/DL.png",
  ),
  Brands(
    id: 2,
    name: "استم سل",
    latinName: "Stem Cell",
    image: "images/SC.png",
  ),
  Brands(
    id: 3,
    name: "میلیتو",
    latinName: "Milito",
    image: "images/m.png",
  ),
  Brands(
    id: 4,
    name: "راکوتن",
    latinName: "Racuten",
    image: "images/DL.png",
  ),
  Brands(
    id: 5,
    name: "لاکوئینتا",
    latinName: "La Quinta",
    image: "images/SC.png",
  ),
  Brands(
    id: 6,
    name: "توتال درم",
    latinName: "Total Derm",
    image: "images/m.png",
  ),
  Brands(
    id: 7,
    name: "دلانو",
    latinName: "Delano",
    image: "images/DL.png",
  ),
  Brands(
    id: 8,
    name: "بایوریچ",
    latinName: "Bio Reach",
    image: "images/SC.png",
  ),
  Brands(
    id: 9,
    name: "پلزنت",
    latinName: "Pleasent",
    image: "images/m.png",
  ),
  Brands(
    id: 10,
    name: "ادلیو",
    latinName: "Adelio",
    image: "images/DL.png",
  ),
  Brands(
    id: 11,
    name: "فارمالاین",
    latinName: "FarmaLine",
    image: "images/SC.png",
  ),
  Brands(
    id: 12,
    name: "جوجو",
    latinName: "JOJO",
    image: "images/m.png",
  ),
  Brands(
    id: 13,
    name: "رینکن",
    latinName: "Rinkon",
    image: "images/DL.png",
  ),
  Brands(
    id: 14,
    name: "بتیس",
    latinName: "Betis",
    image: "images/SC.png",
  ),
];

List<Products> productsData = [
  // DERMALIFT Products
  Products(
    id: 0101,
    name: 'کرم روشن کننده قوی ملالیفت',
    latinName: 'MELALIFT Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'روشن کننده قوی پوست',
      'محافظ پوست در برابر اشعه ماورا بنفش نور خورشید',
      'برطرف کننده تیرگیهای پوستی در اثر عوامل مختلف',
      'رفع لکهای مقاوم به درمان',
      'حفظ شادابی و طراوت پوست',
      'حاوی قوی ترین و جدید ترین ترکیبات روشن کننده پوست',
    ],
    activeIngredients: [
      'HIEROGALINE',
      '4 N BUTYLRESORCINOL',
      'ASPARLYNE',
      'FUCOGEL',
      'POTASSIUM AZELOYL DIGLYCINATE',
    ],
    image: 'images/DL-keremSebolift.png',
    method:
        'روزانه دو بار کرم ملالیفت را بر روی مناطق تیره پوست مالیده و به خوبی ماساژ دهید. در طی روز حتما از کرم ضد آفتاب با SPF مناسب استفاده نمائید.',
  ),
  Products(
    id: 0102,
    name: 'کرم آنتی آکنه سبولیفت',
    latinName: 'SEBOLIFT Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'درمان سریع آکنه های التهابی و چرکی',
      'برطرف کننده کومدونهای سر سیاه و سر سفید',
      'تنظیم و کنترل مناسب چربی، مهار آنزیم تولید کننده چربی',
      'ضد باکتری و ضد قارچ',
      'کاهش سطح لایه شاخی مجاری غدد چربی و درمان اسکار ناشی از آکنه',
    ],
    activeIngredients: [
      'SEBOXYL',
      'ENCAPSULATED',
      'ASPARLYNE',
      '5 ALPHA AVOCUTA',
      'FUCOGEL',
      'ZINC PCA',
    ],
    image: 'image',
    method:
        'پس از شستشوی مناسب پوست، روزانه دو بار کرم سبولیفت را روی مناطقی از پوست که دچار آکنه و کومدون گردیده اند، مالیده و به خوبی ماساژ دهید.',
  ),
  Products(
    id: 0103,
    name: 'کرم ضد تیرگی و التیام بخش دور چشم ویتالیفت',
    latinName: 'VITALIFT Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'کاهش حلقه های تیره دور چشم',
      'ضد التهاب و التیام بخش پوست دور چشم',
      'رفع کننده کبودی دور چشم',
      'افزایش گردش خون پوست دور چشم',
      'دارای خاصیت مرطوب کنندگی و ضد پیری',
      'حاوی کمپلکسی انکپسوله از ویتامینهای موثر در رفع تیرگی دور چشم',
    ],
    activeIngredients: [
      'LIPOSOMAL VITAMINS (A, C, E, B5, K)',
      'ENCAPSULATED CAFFEINE',
      'ASPARLYNE',
      'UNISOOTH EG',
      'FUCOGEL',
      'SWEETONE',
    ],
    image: 'image',
    method:
        'ترجیحا شبها کرم دور چشم ویتالیفت را از سمت داخل به خارج پلک تحتانی با حرکات ضربه ای ملایم بمالید. مراقب باشید کرم داخل چشم نگردد. کرم دور چشم را حداقل به مدت شش ماه استفاده نمائید.',
  ),
  Products(
    id: 0104,
    name: 'کرم ضد قرمزی رزالیفت',
    latinName: 'ROSALIFT Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'رفع کننده سرخی و قرمزی پوست',
      'کمک به رفع التهاب پوستی',
      'تسکین دهنده و ضد التهاب پوست',
      'حفظ شادابی و طراوت پوست',
      'فاقد ترکیبات استروئیدی',
    ],
    activeIngredients: [
      'ASPARLYNE',
      'SWEETONE',
      'FUCOGEL',
      'CLARITEA',
    ],
    image: 'image',
    method:
        'کرم رزالیفت را روزانه 2 تا 3 بار بر روی مناطقی از پوست که دچار قرمزی یا التهاب گردیده اند، بمالید. مصرف کرم را تا رفع کامل قرمزی و التهاب ادامه دهید.',
  ),
  Products(
    id: 0105,
    name: 'کرم سفت کننده و لیفتینگ پوست فرمالیفت',
    latinName: 'FIRMALIFT Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'سفت کننده و لیفتینگ پوست',
      'افزایش دهنده قوام و استحکام پوست',
      'محرک ساخت رشته های کلاژن و الاستین و جلوگیری از تخریب آنها',
      'محافظت از پوست در برابر اثرات مضر اشعه UV',
      'حفظ رطوبت لایه شاخی پوست',
      'افزایش متابولیسم و انرژی سلولهای پوست',
      'حفظ طراوت، شادابی و جوانی پوست',
    ],
    activeIngredients: [
      'ASPARLYNE',
      'COLLAGENEER',
      'FUCOGEL',
      'Actimp',
    ],
    image: 'image',
    method:
        'پس از شستشوی مناسب پوست، کرم فرمالیفت را صبحها و شبها بر روی پوست صورت و گردن مالیده و به خوبی ماساژ دهید.',
  ),
  Products(
    id: 0106,
    name: 'کرم مرطوب کننده قوی هیدرالیفت',
    latinName: 'HYDRALIFT Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'افزایش میزان فاکتورهای مرطوب کننده طبیعی پوست',
      'آبرسانی به عمیق ترین لایه های پوست با اثر 24 ساعته',
      'کاهش تبخیر سطحی و حفظ رطوبت لایه شاخی پوست',
      'نرم کننده و التیام بخش مناسب',
      'بازسازی سد دفاعی پوست',
      'حفظ شادابی و طراوت پوست',
    ],
    activeIngredients: [
      'SODIUM LACTATE',
      'UNIMOIST',
      'ASPARLYNE',
      'SOLINE',
      'FUCOGEL',
      'AVOCADO OIL',
    ],
    image: 'image',
    method:
        'کرم مرطوب کننده هیدرالیفت را روزها و شبها به دفعات مورد نیاز به روی پوست صورت و گردن مالیده و به ملایمت ماساژ دهید تا جذب گردد. از این کرم می توانید زیر آرایش نیز استفاده کنید.',
  ),
  Products(
    id: 0107,
    name: 'شامپو ضد ریزش و تقویت کننده مو',
    latinName: 'VITA-GROW',
    categoryId: 2,
    brandId: 1,
    discription: [
      'کمک به رفع ریزش موی سر با علل مختلف',
      'تقویت رشد فولیکولهای ضعیف موی سر',
      'پیشگیری از پیری و سفید شدن موهای سر',
      'کاهش دهنده ترشحات غدد چربی پوست سر',
      'احیا کننده موهای خشک و آسیب دیده و پیشگیری از ایجاد موخوره',
      'جلوگیری از ایجاد بوی نامناسب پوست سر',
      'مناسب جهت مصرف بانوان و آقایان',
      'فاقد سولفات، فاقد نمک، فاقد پارابن',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0108,
    name: 'شامپو ضد شوره',
    latinName: 'VITA-KER',
    categoryId: 2,
    brandId: 1,
    discription: [
      'رفع کامل شوره های خشک و شوره های چرب و مقاوم به درمان',
      'کاهش قرمزی، خارش و حساسیت پوست سر',
      'جلوگیری از رشد باکتریها و قارچ های مولد شوره',
      'احیا کننده موهای خشک و آسیب دیده و پیشگیری از ایجاد موخوره',
      'تنظیم کننده ترشحات غدد چربی پوست سر',
      'مناسب جهت مصرف بانوان و آقایان',
      'فاقد سولفات، فاقد نمک، فاقد پارابن',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0109,
    name: 'شامپو مناسب موهای رنگ شده',
    latinName: 'VITA-COLOR',
    categoryId: 2,
    brandId: 1,
    discription: [
      'کمک به تثبیت رنگ مو و جلوگیری از کدر شدن موها',
      'مراقبت کامل رنگ موها در برابر اشعه UV نور خورشید',
      'نرم کننده و حالت دهنده موهای رنگ شده',
      'جلوگیری از ایجاد موخوره، زبری و خشکی موها',
      'فاقد سولفات، فاقد نمک، فاقد بارابن',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0110,
    name: 'شامپو مناسب موهای وزدار',
    latinName: 'VITA-FRIZZ',
    categoryId: 2,
    brandId: 1,
    discription: [
      'صاف کننده موهای وزدار و مجعد',
      'ایجاد لایه محافظ بر روی تار مو',
      'افزایش نرمی و لطافت ساقه مو',
      'جلوگیری از ایجاد موخوره',
      'تغذیه کننده و آبرسان موهای وزدار',
      'فاقد سولفات، فاقد نمک، فاقد پارابن',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0111,
    name: 'فوم بعد از کاشت مو',
    latinName: 'VITA-PLANT',
    categoryId: 5,
    brandId: 1,
    discription: [
      'مناسب شستشوی موهای سر پس از پیوند مو با روش های مختلف',
      'کاهش التهابات، سوزش و خارش پوست سر',
      'کمک به کاهش درد و احساس کشیدگی پس از عمل پیوند مو',
      'افزایش خون رسانی و تقویت فولیکولهای پیوند یافته',
      'افزایش رطوبت رسانی به سطح پوست سر',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0112,
    name: 'شامپو بدن ضد قارچ',
    latinName: 'VITA-BODY',
    categoryId: 2,
    brandId: 1,
    discription: [
      'کمک به رفع بیماری های قارچی سطح پوست',
      'برطرف کننده بوی نامطبوع بدن',
      'التیام بخش و نرم کننده پوست بدن',
      'دارای خاصیت آنتی باکتریال و آنتی میکروبیال',
      'فاقد سولفات، فاقد نمک و فاقد پارابن',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0113,
    name: 'شامپو بدن کرمی',
    latinName: 'VITA-SENSE',
    categoryId: 2,
    brandId: 1,
    discription: [
      'مناسب پوستهای خشک، حساس و مستعد اگزما',
      'جلوگیری از ایجاد خشکی، زبری و خارش پوست',
      'مناسب افراد مبتلا به اگزما، درماتیک آتوپیک و پسوریازیس',
      'حاوی کرم مرطوب کننده جهت حفظ لطافت و نرمی پوست',
      'فاقد سولفات، فاقد نمک و پارابن',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0114,
    name: 'کرم مرطوب کننده بدن هیدرالیفت',
    latinName: 'HYDRALIFT Body Cream',
    categoryId: 1,
    brandId: 1,
    discription: [
      'مناسب پوست های معمولی تا خشک',
      'افزایش دهنده نرمی و لطافت پوست',
      'کمک به درمان خشکی، زبری و حفظ شادابی و طراوت پوست',
      'کاهش تبخیر سطحی و حفظ رطوبت لایه شاخی پوست',
      'آبرسانی به عمیق ترین لایه های پوست با اثر 24 ساعته',
      'نرم کننده، التیام بخش مناسب و بازسازی کننده سد دفاعی پوست',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0115,
    name: 'پن شفاف مرطوب کننده هیدرالیفت',
    latinName: 'HYDRALIFT Pan',
    categoryId: 6,
    brandId: 1,
    discription: [
      'مناسب پوست های معمولی تا خشک',
      'افزایش دهنده نرمی و لطافت پوست',
      'کمک به درمان خشکی، زبری و حفظ شادابی و طراوت پوست',
      'کاهش تبخیر سطحی و حفظ رطوبت لایه شاخی پوست',
      'آبرسانی به عمیق ترین لایه های پوست با اثر 24 ساعته',
      'نرم کننده، التیام بخش مناسب و بازسازی کننده سد دفاعی پوست',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),
  Products(
    id: 0116,
    name: 'فوم مرطوب کننده هیدرالیفت',
    latinName: 'HYDRALIFT Foam',
    categoryId: 5,
    brandId: 1,
    discription: [
      'مناسب پوست های معمولی تا خشک',
      'افزایش دهنده نرمی و لطافت پوست',
      'کمک به درمان خشکی، زبری و حفظ شادابی و طراوت پوست',
      'کاهش تبخیر سطحی و حفظ رطوبت لایه شاخی پوست',
      'آبرسانی به عمیق ترین لایه های پوست با اثر 24 ساعته',
      'نرم کننده، التیام بخش مناسب و بازسازی کننده سد دفاعی پوست',
    ],
    activeIngredients: [],
    image: 'images/DL-keremSebolift.png',
    method: '',
  ),

// Stem Cell Products
  Products(
    id: 0201,
    name: 'شامپو گیاهی مخصوص موهای رنگ شده',
    latinName: 'Color Therapy',
    categoryId: 2,
    brandId: 2,
    discription: [
      'عدم نیاز به مصرف نرم کننده و ماسک داخل حمام',
      'فاقد سولفات، پارابن، دی اکسان و سایر ترکیبات مضر و زیان بار برای پوست و مو',
      'بستن سریع کوتیکولهای سطح ساقه مو و محافظت از مرکز ساقه مو از انحلال و از بین رفتن رنگ مو زیر دوش',
    ],
    activeIngredients: [
      'عصاره ریشه آپونتیا',
      'پروتئین هیدرولیز شده سبزیجات',
    ],
    image: 'image',
    method: '',
  ),
  Products(
    id: 0202,
    name: 'شامپو گیاهی مخصوص موهای خشک و آسیب دیده',
    latinName: 'Dry & Damage Therapy',
    categoryId: 2,
    brandId: 2,
    discription: [
      'عدم نیاز به مصرف نرم کننده و ماسک داخل حمام',
      'تنها شامپوی ایرانی بعد از کراتین، دکلره و رنگ مو',
      'فاقد سولفات، پاربن، دی اکسان و سایر ترکیبات مضر و زیان بار برای پوست و مو',
      'ترمیم سریع و عمقی ساقه مو، موخوره و رطوبت رسانی بالای مو',
      'ایجاد حس ابریشمی، نرمی، شانه پذیری بسیار بالا و براقیت پس از دوره استفاده',
    ],
    activeIngredients: [
      'روغن آرگان',
      'شی باتر',
      'روغن جوانه گندم',
    ],
    image: 'image',
    method: 'method',
  ),
];
